apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app_name }}-svc
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app_name }}
	{{- with .Values.Labels }}
        {{- toYaml . | nindent 4 }}
        {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.target_port }}
      protocol: TCP
      # name: http
  selector:
    app: {{ .Values.app_name }}
