{{- if .Values.istio.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.app_name }}-vs
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app_name }}
	{{- with .Values.Labels }}
        {{- toYaml . | nindent 4 }}
        {{- end }}
spec:
  {{- if eq .Values.istio.gateway "" }}
  hosts:
    - {{ .Values.app_name }}-svc.{{ .Values.namespace }}.svc.cluster.local
  {{- end }}
  {{- if ne .Values.istio.gateway "" }}
  hosts:
    - {{ quote .Values.istio.hosts }}
  gateways:
    - {{ .Values.istio.gateway }}
  {{- end }}
  http:
  - match:
    - uri:
        prefix: {{ .Values.istio.prefix }}
      queryParameters:
        {{ .Values.istio.parameter_name }}:
          exact: {{ .Values.istio.parameter_value }}
    {{- if ne .Values.istio.rewite "" }}
    rewrite:
      uri: {{ .Values.istio.rewrite }}   
    {{- end }}
    route:
      - destination:
          host: {{ .Values.app_name }}-svc.{{ .Values.namespace }}.svc.cluster.local
          subset: testversion-{{ .Values.version }}
          port:
            number: {{ .Values.service.port }}
  - match:
    - uri:
        prefix: {{ .Values.istio.prefix }}
    {{- if ne .Values.istio.rewite "" }}
    rewrite:
      uri: {{ .Values.istio.rewrite }}   
    {{- end }}
    route:
      - destination:
          host: {{ .Values.app_name }}-svc.{{ .Values.namespace }}.svc.cluster.local
          subset: primary
          port:
            number: {{ .Values.service.port }}
{{- end }}