{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.app_name }}-sa
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app_name }}
	{{- with .Values.Labels }}
        {{- toYaml . | nindent 4 }}
        {{- end }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
